unit test in sequence 4

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -21,8 +21,6 @@ jobs:
         run: npm clean-install
       - name: Run linter
         run: npm run lint
-
-
   unit-tests:
     needs: lint
     runs-on: ubuntu-latest
@@ -36,10 +34,10 @@ jobs:
         run: npm clean-install
       - name: Run unit tests
         run: npm run test-unit
-      - if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: unit-test-${{ github.sha }}
-          path: reports/report.xml
+#      - if: success() || failure()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: unit-test-${{ github.sha }}
+#          path: reports/report.xml
 
 
